import std/[sets]

proc generateRuntime*(includes: HashSet[string]): string =
  result &= "/*\nKovylang (Kovy) © xlebore3o4ka 2026 copyright\nGenerated by kovylc\n*/\n"
  for name in includes:
    result &= "#include " & name & "\n"

proc runtimeIncludes*(): HashSet[string] = 
  ["<stddef.h>", "<stdint.h>", "<stdbool.h>"].toHashSet