import ../core/[ast, tokens, types]
import std/[sets, strutils]
import codegenSanitizers

const TAB_WIDTH = 2

type
  Context = ref object
    includes: HashSet[string]
    code: string

    indent: Natural
    nameCounter: Natural

proc emit(ctx: Context, code: varargs[string, `$`]) =
  let joined = code.join("")
  for line in joined.splitLines():
    if line.len > 0:
      ctx.code &= " ".repeat(ctx.indent) & line & "\n"
    else:
      ctx.code &= "\n"

proc ctype(ctx: Context, typ: Type): string =
  case typ.kind:
  of typeUndefined: return "void"
  of typeInt64: return "int64_t"
  of typeBool: return "bool"

proc generateUniqueName(ctx: Context, prefix: string): string =
  result = "_" & prefix & "_" & $ctx.nameCounter
  ctx.nameCounter.inc

proc visit(ctx: Context, node: Expression): string
proc visit(ctx: Context, node: Statement)

proc visitNumberExpression(ctx: Context, node: NumberExpression): string =
  return node.token.lexeme

proc visitBoolExpression(ctx: Context, node: BoolExpression): string =
  return node.token.lexeme

proc visitUnaryExpression(ctx: Context, node: UnaryExpression): string =
  return node.token.lexeme & ctx.visit(node.value)

proc visitBinaryExpression(ctx: Context, node: BinaryExpression): string =
  var op = node.token.lexeme

  let left = ctx.visit(node.left)
  var right = ctx.visit(node.right)

  if   node.token.kind == tkAnd: op = "&&"
  elif node.token.kind == tkOr:  op = "||"
  elif node.token.kind == tkSlash:
    let name = ctx.generateUniqueName("temp")
    ctx.emit(ctx.ctype(node.right.exprType), " ", name, " = ", right, ";")
    right = name
    ctx.emit(generateZeroDivisionSanitizer(right, node.right.token.line))

  return "(" & left & " " & op & " " & right & ")"

proc visitIdentExpression(ctx: Context, node: IdentExpression): string =
  node.token.lexeme

# STATEMENTS


proc visitBlockStatement(ctx: Context, node: BlockStatement) =
  ctx.indent += TAB_WIDTH
  for stmt in node.statements:
    ctx.visit(stmt)
  ctx.indent -= TAB_WIDTH

proc visitDeclarationStatement(ctx: Context, node: DeclarationStatement) =
  ctx.emit(ctx.ctype(node.valueType), " ", node.name.lexeme, " = ", ctx.visit(node.value), ";")

proc visitAssignmentStatement(ctx: Context, node: AssignmentStatement) =
  ctx.emit(ctx.visit(node.left), " = ", ctx.visit(node.right), ";")

proc visitBranchingStatement(ctx: Context, node: BranchingStatement) =
  ctx.emit("if (", ctx.visit(node.condition), ") {")
  ctx.visit(node.ifBlock)
  ctx.emit("}")
  
  for elifBranch in node.elifBranches:
    ctx.emit("else if (", ctx.visit(elifBranch.cond), ") {")
    ctx.visit(elifBranch.elifBlock)
    ctx.emit("}")
  
  if node.elseBlock != nil:
    ctx.emit("else {")
    ctx.visit(node.elseBlock)
    ctx.emit("}")

proc visitWhileStatement(ctx: Context, node: WhileStatement) =
  ctx.emit("while (", ctx.visit(node.condition), ") {")
  ctx.visit(node.whileBlock)
  ctx.emit("}")

proc visitContinueStatement(ctx: Context, node: ContinueStatement) =
  ctx.emit("continue;")

proc visitBreakStatement(ctx: Context, node: BreakStatement) =
  ctx.emit("break;")

proc visit(ctx: Context, node: Expression): string =
  case node.kind:
  of exprNumber: return visitNumberExpression(ctx, NumberExpression(node))
  of exprBool: return visitBoolExpression(ctx, BoolExpression(node))
  of exprUnary: return visitUnaryExpression(ctx, UnaryExpression(node))
  of exprBinary: return visitBinaryExpression(ctx, BinaryExpression(node))
  of exprIdent: return visitIdentExpression(ctx, IdentExpression(node))
  else: discard

proc visit(ctx: Context, node: Statement) =
  case node.kind:
  of stmtBlock: visitBlockStatement(ctx, BlockStatement(node))
  of stmtDeclaration: visitDeclarationStatement(ctx, DeclarationStatement(node))
  of stmtAssignment: visitAssignmentStatement(ctx, AssignmentStatement(node))
  of stmtBranching: visitBranchingStatement(ctx, BranchingStatement(node))
  of stmtWhile: visitWhileStatement(ctx, WhileStatement(node))
  of stmtContinue: visitContinueStatement(ctx, ContinueStatement(node))
  of stmtBreak: visitBreakStatement(ctx, BreakStatement(node))
  else: discard

proc generate*(node: Statement, release: bool = false): string =
  let ctx = Context(includes: ["<stdbool.h>", "<stdint.h>", "<stdio.h>", "<stdlib.h>"].toHashSet)

  ctx.emit(generateDebugDefine(release))

  ctx.emit(generatePanicSystem("kovypanic"))

  ctx.emit("int main() {")
  ctx.visit(node)
  ctx.emit("fprintf(stdout, \"%d\", result_);")
  ctx.emit("}")
  
  for name in ctx.includes:
    ctx.code = "#include " & name & "\n" & ctx.code
  ctx.code = "/*\nKovylang (Kovy) © xlebore3o4ka 2026 copyright\nGenerated by kovylc\n*/\n" & ctx.code

  return ctx.code
