/*
Kovylang (Kovy) © xlebore3o4ka 2026 copyright
Generated by kovylc
*/
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#define KOVYDEBUG 1

typedef struct {
  const char* kind;
  const char* message;
} kovypanic_Panic;

typedef bool (*kovypanic_PanicHandler_t)(const kovypanic_Panic*);
static kovypanic_PanicHandler_t kovypanic_PanicHandler = NULL;

void kovypanic_setPanicHandler(kovypanic_PanicHandler_t handler) {
  kovypanic_PanicHandler = handler;
}
void kovypanic(const char* kind, const char* message, int64_t line) {
  kovypanic_Panic p = { kind, message };
  if (kovypanic_PanicHandler != NULL) {if (kovypanic_PanicHandler(&p)) return;}
  fprintf(stderr, "Panic at line %lld: %s [%s]\n", (long long)line, message, kind);
  exit(1);
}

int64_t apply_(int64_t (*f_)(int64_t, int64_t), int64_t a_, int64_t b_) {
  return f_(a_, b_);
}
int64_t add_(int64_t a_, int64_t b_) {
  return (a_ + b_);
}

int main() {
  int64_t result_ = apply_(add_, 10, 20);
}
