/*
Kovylang (Kovy) © xlebore3o4ka 2026 copyright
Generated by kovylc
*/
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#define KOVYDEBUG 1

typedef struct {
  const char* kind;
  const char* message;
} kovypanic_Panic;

typedef bool (*kovypanic_PanicHandler_t)(const kovypanic_Panic*);
static kovypanic_PanicHandler_t kovypanic_PanicHandler = NULL;

void kovypanic_setPanicHandler(kovypanic_PanicHandler_t handler) {
  kovypanic_PanicHandler = handler;
}
void kovypanic(const char* kind, const char* message, int64_t line) {
  kovypanic_Panic p = { kind, message };
  if (kovypanic_PanicHandler != NULL) {if (kovypanic_PanicHandler(&p)) return;}
  fprintf(stderr, "Panic at line %lld: %s [%s]\n", (long long)line, message, kind);
  exit(1);
}

  
int main() {
  int64_t x_ = 0;
  int64_t _temp_0 = x_;
  #if KOVYDEBUG
  if (_temp_0 == 0) {kovypanic("ZeroDivision", "Zero division", 2);}
  #endif
  int64_t y_ = (10 / _temp_0);
}
