/*
Kovylang (Kovy) © xlebore3o4ka 2026 copyright
Generated by kovylc
*/
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#define KOVYDEBUG 1

typedef struct {
  const char* kind;
  const char* message;
} kovypanic_Panic;

typedef bool (*kovypanic_PanicHandler_t)(const kovypanic_Panic*);
static kovypanic_PanicHandler_t kovypanic_PanicHandler = NULL;

void kovypanic_setPanicHandler(kovypanic_PanicHandler_t handler) {
  kovypanic_PanicHandler = handler;
}
void kovypanic(const char* kind, const char* message, int64_t line) {
  kovypanic_Panic p = { kind, message };
  if (kovypanic_PanicHandler != NULL) {if (kovypanic_PanicHandler(&p)) return;}
  fprintf(stderr, "Panic at line %lld: %s [%s]\n", (long long)line, message, kind);
  exit(1);
}

int64_t gcd_(int64_t a_, int64_t b_) {
  while ((b_ != 0)) {
    int64_t t_ = b_;
    b_ = (a_ % b_);
    a_ = t_;
  }
  return a_;
}

int main() {
  int64_t result_ = gcd_(15, 12);
fprintf(stdout, "%lld", result_);
}
